[package]
name = "rs-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.17"
# this is the development version of Yew
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
